name: DEPLOY MAIN JEVON API

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Golang Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.25.3

      - name: Linting Code
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.13.2

  test:
    name: Golang Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.25.3

      - name: Testing Code
        run: go test ./... -v -cover

  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.AUTH_GITHUB_TOKEN }}

      - name: Build Image & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ vars.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}
